app:
  build: .
  links:
   - rethinkdb
  ports:
   - "3001:8091"
  environment:
   - VIRTUAL_HOST=rethink-liveblog.dalanmiller.com

rethinkdb:
  image: rethinkdb
  ports:
   - "11001:8080"
   - "11002:28015"
   - "11003:29015"
 
